---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  main:
    type: daemonset
    containers:
      wireguard:
        env:
          TZ: Europe/Vienna
          PUID: "1000"
          PGID: "1000"
          LOG_CONFS: "false"
        image:
          repository: docker.io/linuxserver/wireguard
          tag: 1.0.20250521-r0-ls92
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
            drop:
              - ALL
          privileged: true

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
    - effect: NoSchedule
      key: node-type
      operator: Equal
      value: agent

service:
  wg:
    type: LoadBalancer
    controller: main
    annotations:
      metallb.io/loadBalancerIPs: 192.168.178.200
      metallb.io/allow-shared-ip: "shared-hl-ip"
    ports:
      wg-udp:
        port: 51820
        protocol: UDP

persistence:
  config:
    enabled: true
    type: secret
    name: wg-config
    globalMounts:
      - path: /config/wg_confs
        readOnly: true
