apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
type: Opaque
stringData:
    github: ENC[AES256_GCM,data:XBe9LoyoXYRRq5f7mX7VHBz1pTc/5Pqtu8a5/N9sIm5FELktuToP9Q==,iv:xv7dK9llv0rF+Dvw3MK7LRtstTKv9eZ2g3AxArEpAxE=,tag:9Y/XH7yrlKIESqzOQuia5w==,type:str]
    gitea: ENC[AES256_GCM,data:UxhUCdoRy0FuVSfMvR87Auproi5Pmd6jxD5rNXzXEdjJzhRg5MI5TQ==,iv:CY4JWj8uY1ycZ6ceovSBsbmLCs3MlMdxvji9Lc9vEDU=,tag:IERX7q6hJHazGgwjNUn8Qw==,type:str]
sops:
    age:
        - recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeXlpUVpJQzlRZlJPOERw
            OVlUdExCeldNVjlXWmxla251VVJhdWJVZmdjCmwveFBEclV3eUxDa21HRHl2akdi
            ZmRXblNOLzhyYWVlTWQ4ZXUvRlJWUmcKLS0tIDNQSnQrSDYzNmpBS3l1dEJTNjZ0
            YzVTVTdpdjYvN3J4UmVDRWZXOWZ6a28K79l0Im8Q8YVJghpJgauTGOGTKe0yVWC6
            I4UbC37u39DOMueQSKBR8HrVjAWoz/WxNoo6tjRs5yi4UgCedzVWYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T20:18:48Z"
    mac: ENC[AES256_GCM,data:vvfPTMtytVu57EQ3roPoXjxAk3qStxigBkv3dVw7qOqLDOXi9cMtq8UHLFFdwaO5UcIQxQr+LiKPsERW6VfmuXhqNBHXzmJS9iE/LvzyBcVkN14T6qtoXw7zdBe2MJskSJf5cTQzLFvtXhJDynupfgg38W/+D4P3Jq7Wa/5kRw8=,iv:cdeMf8FNCMEzqYRonMVhX51IjPc91VLky0Dmfy9xV0M=,tag:5BF60kx/wURGiFjH2YEv7g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
