apiVersion: v1
kind: Secret
metadata:
    name: renovate-signing
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:7O5YBzzURnIOmhG2mjE4N8QhzT1cg8jWvNt1y73eF86CpKbKf3YhAu7+Ox8b1GETLc7KyD2yaVKnidmv7reh7npPXG/Izd9a9gIvUq8o9GsUrkHsKyx0b6rBJFnSMe5qj2r/0+gR+bZhZjwHzsiCtLmDNmvcDmGtRuV4bD6k/wzC5cLlSRCPRCsWVXBWXkhmt6MSWAOOU58z9khxCwxS5mbF6JnR58RRCcBLlUCclXnN6MqIYoGI1cO5NdL1qscOLQmbablC87Q8mNNRhXM3gRT1IgcujQy62fgUBPqIpccu+p6co7scxMg1/2btM0FeCflQMj56Lm63tAYNZPXWEdxRgM+SfvE0FJ1+ACY3klG3spRQkxWFCwdLj89Xqt+u7sGk0UTFnNFz05qThDUTC8uWFAFuALBrLVpvkmbJepE+ggG+69lU1QxZrbBn8EyutGOjUkgyoejQF2lvENeAXB7clQmw2Gj1X8RaPFZkNgua+YuSaOw3s3wfPR409PblYC2Ctmge54pjfOxWFfEy0Xz1WZ93jW3NzIfXmCLFrT2+JsgWNkKFLnf9Bm6xnSW8xVhqmbCdZzpcQM0M,iv:7eSC1I5gYD6eam0Wwd9I1YeAXb8FCzM4Z1gPXJNltZA=,tag:TaiDZfhXYzEZdA+4dYRcHg==,type:str]
    password: ENC[AES256_GCM,data:uNo4Piq6uNcC5XBfFxzFi45oIPax4WDFGjmsA1PZFFeRGwAf,iv:ghOGvIAr3UR3YpPMlpmwRUjbQoMFNgy/9rZlxWXtqcQ=,tag:5cTSBjqzWeYFe8t6Rx6AcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaFZjbWpmeDg1K2pxOXJK
            MGJnM052bnVucHNpbzdiSTJnei84SWxzYUFJCkhieXNCYnBIdFNYSzBPZUZTQTBm
            bjg1RGlrd2IwWFRXdzV2a3dIbWwzOTgKLS0tIHJ2bUdXcTY1THVud2lGZGxneEF2
            Y0FHajhjeWRoNGJEZERNZWxNcStJQ1kKG3nW8ThQqBf5ADaJGtIWdwdLcoNg9XQF
            2rnJh7Op1sw54dY5fGzWFB1MUmXUTbwd/cNtItz6HYTGR2U7LVtuGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIajFKdmM4WnVyMVZDOHBr
            U01MRGhFWjVqb29wQ0J0TVUyMHdKSG15bUd3Ckw3UjJRbjc1bmlLenV6M1RBMXVH
            T3JneEx0Mm01YTFNNXhuL0pOaG9rdU0KLS0tIDJDQ0ZHUUhBaEhYRTA5SndOUEQ0
            NUN0YmdJR21oY2Z2bzgvR0J3RW1XbkEKyFQd1cBxAbQ3pTTDIplkLO3rXn3UI8Hk
            wEw49bAaTvUkltDJIbUbnrsSqJdNSs08neQ+96mLqPoZpok3UAD2tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzwgfr26gd9eus80ydsskdkp4gh6az5vr78cvd6zzamh35snz4hq5x3whm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL2ZKeG5yVmtYQ1hldW9J
            aWpkVTlJbFRHcFZoaGxDdWptVUJwMGFFMWxnCmk5TVIrejdZaVQ0aUpRZVAwTGtj
            eWQvRVlTeko0L2VhajloMjhtNWpITlEKLS0tIGtVSGh5NUo3cFpwUk1MZGJpRGlo
            K1VWdi9sTmsrSUh0NFNoZXl3Mm1uSUkKgFOo6jrh/nQCgrSMmQIJ5mHolOVUhYzJ
            WLV7LetGF+XuaWrFIZz/ncDlOnddFXqlGez7VNcx/mtrLHisPL7vlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgxuzyrc8px3ynsusmnjdsvn3suvgj7ep6re9lvh2vlqkv445skqxz4jed
    lastmodified: "2026-04-20T19:41:13Z"
    mac: ENC[AES256_GCM,data:szfZz/zRy0V/Op+1yCcllNKNLHLkjpszHytNBV/bIy/nfGEuNp3muRCyaQYe1xNMnpfzcnCQ5jm+qpbB9y1aMPOyG9rQSXjrh5+TQDqpK7il3QAJNZGKmCWxDpjhTw+18LkG3lntSttqjbYgOTm7/DUrGIg+e0ahYfS12A+sW7Q=,iv:sBw+GW5rWRhPwSztRINj7deyPO52MU1hXozZbsBSyW0=,tag:51xilzZYHguIxdKVkw4JmA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
