---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - navidrome-lastfm.yaml
  - navidrome-spotify.yaml
  - release.yaml
configMapGenerator:
  - name: navidrome-values
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=values.yaml
