apiVersion: v1
kind: Secret
metadata:
    name: navidrome-lastfm
type: Opaque
data:
    key: ENC[AES256_GCM,data:kaNUxeqHh9P0L2Na0+9O6fBq/HIHutJ2Rt6sZd3aqillW9FdryAUzUHQ6f4=,iv:P0tdJ9iujV0ASmO/2fO2/9fzupe+bcWaQdgjUY9UNw8=,tag:FLxqmQYklk1MQ3FLVlyX/Q==,type:str]
    secret: ENC[AES256_GCM,data:HxdaJL9d5F+xvGnSW+3rCHG5KPcSJ88aWuH7czrmRk1IlNFHrYfEJ/cx1bs=,iv:VJG76g2jqqYwbNYQR0y0Dpglp2ZRvcrvWIXxz0XoKPc=,tag:ort/xbFCr7a5X5rmJhv9Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZTFtSSt1OWs3K21zSTZT
            eXhGVzhucVYrR1c4ODhqSVlDOG1iVnR6NGo4CmRMYUVSZGx6T2ZzNm9vRFVxSDNn
            S2E2cUN6QWJqWHVMaS9YR1JhazRjcmsKLS0tIHJBSTVXTGhhYU1naE9JaWtDaVZT
            anBKQ1crZUgrTFRmaXRJZTM5ZGFDSVEKFxkk62L2aqY+NB/oySrcYwZqd7aJCWgd
            r60c3eh+RuF2BUsVGXeDSOBJaug2fAiMHY/NrC9kjEV+agX1Hvic7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS2ZIWktKU04xQWpGMEsy
            T0hQU2NOQm91TFBBcEh2NVlSMXNubEJUbWxBCmlXTXlKeitZcmZwNTNsRituNjVC
            RFl4cXdVQzhueDFDWWkxOVJTNDRhWlUKLS0tIFU1S3d5RktPaCtRNURkWktERGsz
            WmRsM082SGJEN1ZZaVluNGthb0dURXMK8y8gIHv/3PbbGml2kB/V0bHfxgsEm6hX
            5+TnFbFxLBDMDPRQcIwEndfdKYXH46irbqrVIN0/sDSe9k9wCyeXSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzwgfr26gd9eus80ydsskdkp4gh6az5vr78cvd6zzamh35snz4hq5x3whm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWkdod1d4aWVpRFQ1bzNK
            RVhOL3JlMUpUVDNVRmxmMDZRQ3dBUFFJRjBZCjduUHZiRnNHeHd2T2lpdUN4eTFQ
            ZkgyaU9sY0hVYUM5OFEwUlVxZTg1dmsKLS0tIEw4bzdTb3RjT2Q3OG5sMWh0TGln
            SXhFUHlFeVd3SWlxTWREUVRwRkhFREUKovdyGP+/ox8EgeOAW8owtrMWdiJdlIsi
            DmKodc5sTbunWuVrYeI04ONcfU8GucQUUtGDlJQxdQ0QPaMTsE731g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgxuzyrc8px3ynsusmnjdsvn3suvgj7ep6re9lvh2vlqkv445skqxz4jed
    lastmodified: "2025-06-16T16:06:40Z"
    mac: ENC[AES256_GCM,data:zAoA5FHV71uhahbyNaAmzKtRiPU7rlyU8VmykFUy1f3N0htqnCpL9+9h4VfXaHgh+WBkJs0vp8mIVBURv68kPzDFSISrBFOJoN197faNfKpfr5x7Infic5Cb27wLmREaLuDifVjNyNexqX138Ha+u7hvpeAqtRUIySu+eWsdbMI=,iv:2p2VNQQm1ar5oSmFPpex9bRPiTFhC3etXcmec6IvWQY=,tag:UC4PwyxXcv9mwB5FFeqMmg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
