apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
type: Opaque
data:
    username: ENC[AES256_GCM,data:fry6U1qgRDuX814Y,iv:L0y6s0mUIFTRIF4eZG1q1o2/Wv/wW9ttv+9RJUODe5I=,tag:x2hnK7asnDSCUiQZkw9gWw==,type:str]
    password: ENC[AES256_GCM,data:eUCTuTJihGaQyIZSnUvHxi/sV5UXcnmFC8nnTvVfpTaJ4dtH6gIS47SHUb09h6ge,iv:UP9MZMs5ciSsf2xFxQkPiSqEhGlgFnLm6QhqoQEnkwY=,tag:VjirJos96Ynjpx1Aszj49A==,type:str]
    email: ENC[AES256_GCM,data:+YsL01ajwYYcabnnwEOd9sRpw0gToXUC/Jpp4A==,iv:/2QOXqazY+HOwBFMSxoB3/FrUjN28GHPUyOy7VoPzB4=,tag:o0cGfeaZiIXOiFrBKlHG8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK3YxSjZFeU5tbENXNGNL
            YnkrTzV6WDZxYURBamorQTZFRmkrOEtCVGc0CndFV2ZGZjQ0NUZhUGhONDZBQkZn
            OFVSK2RHQzB3SDMzUlVMQzZoUHBESEkKLS0tIFJyVEJWdHVlYnZ1NERRdDNra3lw
            eEpEdDZIbTM2c2NVdXZKSnBIeTB4MnMKXS67Sq0zlhgWKpqP51PpXk8MAzsBsh1R
            b8XhPqHxTl/edasz5kPDsHDvyM+9EA/1ROQUO2L1fn5zmkB5YXHTMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY1dYam5NWGEycjF3eGZQ
            U2ZuVWtPU204cldURE1SL1NpRWJWK3ZObVZBCkdOb1duVUprMFNFUHlid2pxVGJT
            RDJMUmFrMXVsMXEvSUZYbVJqZ3hBVXMKLS0tIEJ1dHR2bG9jSXdiRnNTQ2FkTlhO
            SzZsRXNCQ0N2RWZCYlRwNTdmanlkblEK/mCW8DBIdIds/WGtEd7hpQ38lYEdsgxS
            tyer2TaGJg9RBYGCwldgoXMYbHuSEn5kMqv03H6ApNzHrH5XRO0Enw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzwgfr26gd9eus80ydsskdkp4gh6az5vr78cvd6zzamh35snz4hq5x3whm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVG9Jb29SdDhjUVM0OFJo
            dkR4UHZUakdTOWFqcDljV3NuWU1GcWRnb0JnCnIvdzJRYkdKWTdWMENjb3VRMysx
            WUloQnE2VEtDK3FIYnRTbC9DR3lKUEUKLS0tIGNsbUJtNFE5K0RQb2FobjR1Y2Fv
            andjbUpFRGFqYmV0cXZ0MEp1OTNHSUkKYZvDhFlok8vzi6UrTsIxG4+40JH6TEgL
            83Bdbp3npYpPjPI9DxA7y/jt3rdc4PN+/n+87vMIS2OwL70dkflS1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgxuzyrc8px3ynsusmnjdsvn3suvgj7ep6re9lvh2vlqkv445skqxz4jed
    lastmodified: "2025-08-19T19:22:22Z"
    mac: ENC[AES256_GCM,data:AMsPXWWHB0DbmaR0j8NqzYbqAu6MisYSAuSgWexDnfIP9Tg6ARkY5xk09WUrhTv8i6SAD+tnKfFMvzUaqnvMxDTXvCpW4kvHAjecI7zhEOOL7ryWb33WNoB8evmY08FGYq8W9TkNl12z3OVyy8SgDY5IM6gwnfYl0I4pCSChy1g=,iv:ZTOQ5z33Kaljm3SeM5EOhpvjqh5/y4/aRPnGSUlwF/E=,tag:OrBMOg+hvs1L/cNVCELu/Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
