apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:iATS/X/U6O2qLeXbk7ctXR1r17EWPRiqu2rZF6xfpK2dnYFEKNOvCw==,iv:pQo9uRMCIjdDyGIhkcmbuYG5NNo0uGd1IPrEW7YE9Y0=,tag:kXrHaDzvKjdEt4xC9D+K9Q==,type:str]
sops:
    age:
        - recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVUE3L05HVnVKa1QvV2c5
            SkhmTHlIT1ZZWXFRbnVvdzBaMzBxTTFlNVNzCm5SR00xbzl2L0IrcW12eXZ5eGNY
            VUI4L1lnVUtJaWVoL3p4cml2aGw1YjAKLS0tIHJ4RmMybkU4aTdsbzM4dDJEQzNW
            RWNvQm9YS0NoUjdPWjY1N2RNKzhKclEK5EhojgqO+MbROHFBiTvuQz/zt8nwOTiD
            m9wTC13t8nn19S+kH/JIcrWyJEIKcrbUGAb3kpwoB7ClZ5bAN08xvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T14:13:23Z"
    mac: ENC[AES256_GCM,data:pRxLDgLpgbNJBwBGBMVp55WYzmDGnM7gU2jRSsusIt4v2z1NEHL1k3QiT0UrL4bIcK5nCO0ZWZ3ivIMcs8yPV/XsSCaNyQlt4oUzTOD5PJGGTsKGBJ9qqZG3J6bwIIeOA7b/m6DXhWqIWpk0gaUy3FBryWjlR1O7ZhtS3WmNShc=,iv:iMajW1N56hyE2brslpVgBd48j6oUK5nsjWpb2g2FS0A=,tag:5N4ZSaQJYcS4idFHGYRc2g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
