---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:zH/udGE9KFON8884IPjJDcIa3+GIa6JK3GHifpKhy7GffJ6bhCXj5A==,iv:65U5owcubJiGRXTOp09Hmc7ZLJogXUzGSwP0xKtRRlw=,tag:IpvXqhlxH9UioD8iOVrwbg==,type:str]
  uuid: ENC[AES256_GCM,data:O1JO8IrwZVxTg9ba9kCHNQaM5vDyG03/9RZMRpJfj6LW5jTQ,iv:CkN6dYtJl7+OdfXJSyDjjxSx2JF+ZSPqsfLNlGilPe8=,tag:FR1boaBBytIJbXOuzGxHhw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVUE3L05HVnVKa1QvV2c5
        SkhmTHlIT1ZZWXFRbnVvdzBaMzBxTTFlNVNzCm5SR00xbzl2L0IrcW12eXZ5eGNY
        VUI4L1lnVUtJaWVoL3p4cml2aGw1YjAKLS0tIHJ4RmMybkU4aTdsbzM4dDJEQzNW
        RWNvQm9YS0NoUjdPWjY1N2RNKzhKclEK5EhojgqO+MbROHFBiTvuQz/zt8nwOTiD
        m9wTC13t8nn19S+kH/JIcrWyJEIKcrbUGAb3kpwoB7ClZ5bAN08xvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
  lastmodified: "2026-09-13T12:41:22Z"
  mac: ENC[AES256_GCM,data:Yhh2rvTg+IzD7dzwLdnq9CwZgoj18y6z8/iu/Pt/PUAlOUuBu9kZ84vYkW5SSF4GH2JM91UANHEl2lBL6dYl4UB0LGrNc+nDKMmitc+hIE9Pmen7AKlo6miiXGPVGzFdT8nFw4AYT8OwWOxEs6bODrdpvzZtIn7C84/QgbURsAo=,iv:S+5a3GmV+MjpDL2bqQV3wk55AjL6Cf1ImSKk0q0Wx+M=,tag:x/tIOWok3fCQGjNnOL1RmA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.13.3
