[tools]
sops = "3.13.2"
doggo = "1.2.0"
dyff = "1.12.0"
flux2 = "2.9.2"
helm = "4.2.3"
"npm:@immich/cli" = "3.0.3"
"github:coreos/butane" = "0.29.0"
"github:coreos/ignition" = { version = "2.26.0", exe = "ignition-validate" }
"github:ifd3f/caligula" = "0.5.0"

yamllint = "1.38.0"
actionlint = "1.7.12"
python = "3.14"
uv = "0.11.31"
"pipx:flux-local" = "8.4.0"

[env]
IMMICH_INSTANCE_URL = "https://immich.wallstreet30.cc/api"

## flux

[tasks."flux:sync"]
run = """
flux suspend source git flux-system
sleep 5
flux resume source git flux-system
"""

[tasks."flux:test"]
run = "flux-local test --enable-helm -v"

[tasks."flux:diff"]
run = """
DIFF="dyff between --omit-header --color on" \
flux-local diff hr -A
"""

## nix

[tasks."nix:check"]
run = """
nix flake check -L --no-build
"""

[tasks."nix:refresh-flake"]
run = """
nix run .#write-flake
"""

[tasks."nix:update-flake"]
run = """
rm -rf result current
nix run nixpkgs#nixos-rebuild -- build --flake .#hl-server --impure
mv result current
nix flake update --commit-lock-file --option commit-lockfile-summary "chore(flake): update flake.lock"
nix run nixpkgs#nixos-rebuild -- build --flake .#hl-server --impure
nix run nixpkgs#dix -- current result
"""

## hosts

[tasks."all:build"]
run = """
mise run hl-server:build
mise run hl-agent-00:build
mise run hl-agent-01:build
"""

# 192.168.178.100
[tasks."hl-server:build"]
run = """
nix run nixpkgs#nixos-rebuild -- build --flake .#hl-server
"""

[tasks."hl-server:deploy"]
depends = "hl-server:build"
run = """
user="clemens"
ip="192.168.178.100"
host="hl-server"

kubectl scale -n media deployments.apps -l requires-nfs=true --replicas 0 || :
sleep 30

nix run nixpkgs#nixos-rebuild -- boot --sudo --impure --flake .#$host --target-host $user@$ip
sleep 5
ssh $user@$ip -C sudo systemctl reboot
sleep 120

while ! ssh $user@$ip -C exit 0 &> /dev/null; do sleep 5; done;
sleep 30

kubectl scale -n media deployments.apps -l requires-nfs=true --replicas 1 || :
"""

# 192.168.178.101
[tasks."hl-agent-00:build"]
run = """
nix run nixpkgs#nixos-rebuild -- build --flake .#hl-agent-00
"""

[tasks."hl-agent-00:deploy"]
depends = "hl-agent-00:build"
run = """
user="clemens"
ip="192.168.178.101"
host="hl-agent-00"

nix run nixpkgs#nixos-rebuild -- boot --sudo --impure --flake .#$host --target-host $user@$ip
sleep 5
ssh $user@$ip -C sudo systemctl reboot
"""

# 192.168.178.102
[tasks."hl-agent-01:build"]
run = """
nix run nixpkgs#nixos-rebuild -- build --flake .#hl-agent-01
"""

[tasks."hl-agent-01:deploy"]
depends = "hl-agent-01:build"
run = """
user="clemens"
ip="192.168.178.102"
host="hl-agent-01"

nix run nixpkgs#nixos-rebuild -- boot --sudo --impure --flake .#$host --target-host $user@$ip
sleep 5
ssh $user@$ip -C sudo systemctl reboot
"""
