FROM docker.io/longhornio/longhorn-instance-manager:v1.4.1

ENV PATH="${PATH}:/run/wrappers/bin:/run/current-system/sw/bin"

# sudo docker build -t longhornio/longhorn-instance-manager-nix:v1.4.1 .
# sudo docker save longhornio/longhorn-instance-manager-nix:v1.4.1 | sudo k3s ctr images import -
# sudo k3s kubectl apply -f longhorn.yaml -n longhorn-system
