apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:l9P5JsoSf0jHurdnkVR1Ru90VzsI+1DXxD2nJ9C/74vHKPpxFlbP9Q==,iv:yaYGuQOQXMms2ed/FLOqeW40krRKf9hLE6SqBribvqA=,tag:YESKHB/kPY92HTOaxUw9mg==,type:str]
    zone: ENC[AES256_GCM,data:4RI9Xwv2cCyBTKNsQ9VK,iv:mqojwi5mckezeZK5vUzZhrJQazzGO++u25+2LFXUgPo=,tag:lFEBs/Pon5BSkt3scQ2oZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWi84OFE2RlV4Mzk1Vzkx
            RlBOYWRySTFLNklVaVdWVTJuZ2dyMkNidW13Clh2M0pDT3lvL2ZhWGxjUXVDV3Nx
            UU9aeVpOa0N4MThFaG1vMGpPaGJ3RTAKLS0tIHJpenYyR1JDTjRPREgzYlllYkJl
            ZXZxT2tBNjRSb0xhU1NnTXBoSFFMc0kKf3A5el25JBwDffybMt0VaVqfzrCWHi7F
            Whi56Z7V/qqVJH7H4peTzfuDBI/vhbBZipjlVIPbQqS8VFqKLKW9xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUno3MG4ybi95OStYdGRL
            cmErQTNyMkNCN2lReW1FWU1qQS9jK0xXMm5JCkRQN2FIQmN5L3dUaGg1QmlvdnBI
            T2NGckx3Mk8zQ1dyZkcvd0VvUjd0VkEKLS0tIFBlSGY2c0lnOHZSU2ZCdkZnL0gr
            cDJqOWxWdlpKalVaZTAvTitBa3lnT0EK+ChTD0ypCIFLaTSrAtMermHBTS5fuPwz
            c0DMgHntGUv0SVcnJPCYqDb712mD7Mch+vKYdQytVZmaFFj+2I/Gfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzwgfr26gd9eus80ydsskdkp4gh6az5vr78cvd6zzamh35snz4hq5x3whm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmODQ4TmJoWXFqMG1NbXU4
            b0diU2g5ZWtqUXdQTi9RRkp5L2dKM1dXa2owCk9hOTBqOUhOY3lMQTQ3cFM5Unox
            VDRpbktsS0pENGdDVG8yVEVxT3NqYzQKLS0tIDl3UHYvWUlZak5qTTVCTE4yNkZz
            dDdXcEt1REFSN2R6YVdkNW9KRm5NMjQK5Vh4qbzaSzbV5iKSH4TBGwS99mYMwt/e
            JYi6dA3JRqtZCPGPCpvT3SfrEf1EyoVOXxuZ+YhguE5kaZyJFdIXtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgxuzyrc8px3ynsusmnjdsvn3suvgj7ep6re9lvh2vlqkv445skqxz4jed
    lastmodified: "2023-04-18T13:50:20Z"
    mac: ENC[AES256_GCM,data:9W2XKr4cEtlC0pYbrv8kr/v+V0+RLn/L2qlZQG1/8oEAVqKYE4V5TOFiKr2hS0yBHA3moH+BT6p6FmbiseeqEThrZWIrtwYHJLVC+mmyvQu+Aail5zgmGOZa9Cp/JokyZc2xb+9lfRkmoYTU9YBL2Dof6pe7VIn7OMDL7tRkKu4=,iv:zDrprQR4gxHdpXU0PvdpumLHXs/v1z+nzA9IihLPlns=,tag:PVmIwIOyhWnPPxlN3sOn8w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
