# shellcheck disable=all

typeset -U path cdpath fpath manpath
PROMPT_EOL_MARK=""
ZSH_DISABLE_COMPFIX="false"

HISTSIZE="50000"
SAVEHIST="25000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY
unsetopt beep
setopt HIST_SAVE_NO_DUPS

export PATH="$PATH:$HOME/.local/bin"

if [ -n "${CONTAINER_ID}" ]; then
  alias 'hzsh'='distrobox-host-exec zsh'
else
  export ZSH_THEME=robbyrussell
  alias 'db'='distrobox'
fi

# oh-my-zsh
if [ -d "$HOME/.oh-my-zsh" ]; then
  plugins=(git extract rsync)
  ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
  source $HOME/.oh-my-zsh/oh-my-zsh.sh
fi

export LANG='en_US.UTF-8'

# Aliases
alias 'cd..'='cd ..'
alias 'clear'='printf '\''\33c\e[3J'\'''
alias 'q'='exit'

## git
if command -v git &> /dev/null; then
  alias 'gcm'='git commit -v -m'
  alias 'gdc'='git diff --cached'
  alias 'gdm'='git diff --cached master'
  alias 'gfmm'='git fetch origin && git merge origin/master'
  alias 'gprom'='if git branch -a | grep -E '\''remotes/origin/master'\'' > /dev/null; then git pull --rebase origin master; else git pull --rebase origin main; fi'
  alias 'gpskip'='git push -o ci.skip'
  alias 'gs'='git status'
  alias 'gst'='git stash'
  alias 'gstd'='git stash drop'
  alias 'gstp'='git stash pop'
  alias 'gsurr'='git submodule update --remote --rebase'
  alias 'gus'='git reset HEAD'
fi
