apiVersion: v1
kind: Secret
metadata:
    name: slsk-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sRKgkU39Zb71C7zc,iv:TNN+IukNzsoH1JxnOYlIrgqRop530UiJTvkYqDxlVMQ=,tag:pirkewYve3bL7MqiJDsV7Q==,type:str]
    password: ENC[AES256_GCM,data:NkcHom0Wxw9Nzox5nlOlxZgk3TEm7M4JWaOFwhnw71ZDtRbW0qFev9uo,iv:FElbGGqiur1hlVO7M2ZaXcVV7TC19DW50DZBo1tm1NA=,tag:KxEfJ7CdTjETy8YDwgyxew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVlpWYzdmdFJSaXVqRWwy
            NnJ4QzNiRDh5aGhHeTA4N1ZGUm5zbmluMXo0CjFvYUl2M2dyYVczR0RBWnljdGdL
            dDRaWUJIY0xiSm1JQ0Jqd0wwZlhQQjQKLS0tIDl1TGJ1OXN2ZGVyaVd5Y2gzTVA5
            akQ4TVFhdENJaTF1WmJqNUtuVXJQaTAKmAX7h9GraFgr6oSHD7+FnQPHTw9wz9a1
            G4mYQZnV1xdFoAtfSGcaRy1FVARpxlZ8pUlnymNXZDlnliDExWI0Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaXVIcEVZMWZpamFtSWJ1
            L2FFc0NOcUJtTlp2cmo4TjN3eTNFUjdXcG1rCkdJQ0RtL1VGZDJtQk56ZGVvY3Uy
            em5HbklJV0VEQ2FJUjNzT1BtVkFtd0UKLS0tIDczQVBUMHh4cWZrK0d5dC9OQ3F5
            SU5KM2p2RVJYTHZTS2NNb3NSNFRWbEUKHftNUryJ4VPOo5qV5fZnbfuDxvhsmOGE
            QMZ5hbRdtmCAw2MftYqZmNFTuONSoTDQPW/50P9aaFT0Z1wQ/MiuyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzwgfr26gd9eus80ydsskdkp4gh6az5vr78cvd6zzamh35snz4hq5x3whm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbkRUSDFCMmZJWnFqU3hD
            UWJ6cU8yaE0vTWRrdnpzTG9rRXI0RFB6RlJVCjA2dGVia0ZDckZXRjQzWS95MlFv
            VWNLUytTVGFCcnN4L01lSXBrSm96T1UKLS0tIDBUWFB5S00xMlBFMVQ0L1c3Qyt2
            YzIzRFZ5YWp5aXh2L1lzYndBVjdUamMKlr24ugh65XJPWJ46p+2sJywsJDycXYhZ
            Xoy8qlPZnRvyF467lXHFAKj8s2CZPzvV0RKYt2nFuIO9zUaFdXlrtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgxuzyrc8px3ynsusmnjdsvn3suvgj7ep6re9lvh2vlqkv445skqxz4jed
    lastmodified: "2025-08-26T06:53:26Z"
    mac: ENC[AES256_GCM,data:2tCB12nigqabSsN4PIFG1W6ooZJwlh2bDLDy5YVuDVet13nfQUE3As/87hwxH0LFkfgXjAZFjCdB38fOFLmKjKYEG+4t0lBLxnnT0+enx4VsyH/AP6/ZuAoW5kW++C0ShD1nF1fzPBkCgrtOhVvsVDFVYLoSYyebFfPUX9ko8Dk=,iv:L1UFDQ3afgM5lIRuyso/UbyoVR0Ka1nDDZqKIhtK1Lc=,tag:tLI+OAV3VM9XVVSVU2gbpg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
