---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: factorio
  labels:
    ingress: public
spec:
  endpoints:
    - dnsName: factorio.wallstreet30.cc
      recordTTL: 300
      recordType: CNAME
      targets:
        - wallstreet30.cc
