---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-token.enc.yaml
  - discord-alerts.yaml
  - discord-webhook.enc.yaml
  - discord.yaml
  - issuer.yaml
  - longhorn-crypto.enc.yaml
  - longhorn-crypto.yaml
