---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-token.yaml
  - discord-alerts.yaml
  - discord-webhook.yaml
  - discord.yaml
  - ipadresspool.yaml
  - issuer.yaml
  - longhorn-crypto-secret.yaml
  - longhorn-crypto.yaml
  - traefik-config.yaml
patches:
  - target:
      group: ""
      version: v1
      kind: Service
      name: traefik
      namespace: kube-system
    patch: |
      - op: add
        path: /metadata/annotations/metallb.io~1loadBalancerIPs
        value: 192.168.178.200
      - op: add
        path: /metadata/annotations/metallb.io~1allow-shared-ip
        value: "shared-hl-ip"
