---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # https://artifacthub.io/packages/helm/traefik/traefik/40.1.0
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=300s"
      - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=300s"
      - "--entryPoints.web.transport.respondingTimeouts.idleTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=300s"
    deployment:
      replicas: 3
    gateway:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.kubernetes.io/target: wallstreet30.cc
      listeners:
        web:
          namespacePolicy:
            from: All
          protocol: HTTP
          port: 8000
        websecure:
          port: 8443
          protocol: HTTPS
          namespacePolicy:
            from: All
          certificateRefs:
              group: ""
              kind: Secret
              name: wallstreet30-tls
              namespace: kube-system
          mode: Terminate
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
    providers:
      kubernetesGateway:
        enabled: true
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-type
        operator: Equal
        value: agent
