---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # https://artifacthub.io/packages/helm/traefik/traefik/40.1.0
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=300s"
      - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=300s"
      - "--entryPoints.web.transport.respondingTimeouts.idleTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=300s"
    deployment:
      replicas: 3
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
          protocol: HTTP
          port: 8000
        # websecure listener is disabled by default because certificateRefs needs to be added,
        # or you may specify TLS protocol with Passthrough mode and add "--providers.kubernetesGateway.experimentalChannel=true" in additionalArguments section.
        # websecure:
        #   # -- Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules.
        #   # The port must match a port declared in ports section.
        #   port: 8443
        #   # -- Optional hostname. See [Hostname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Hostname)
        #   hostname:
        #   # Specify expected protocol on this listener See [ProtocolType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.ProtocolType)
        #   protocol: HTTPS
        #   # -- Routes are restricted to namespace of the gateway [by default](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.FromNamespaces)
        #   namespacePolicy:
        #   # -- Add certificates for TLS or HTTPS protocols. See [GatewayTLSConfig](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayTLSConfig)
        #   certificateRefs:
        #   # -- TLS behavior for the TLS session initiated by the client. See [TLSModeType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.TLSModeType).
        #   mode:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
    providers:
      kubernetesGateway:
        enabled: true
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-type
        operator: Equal
        value: agent
