---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - dns.yaml
  - release.yaml
configMapGenerator:
  - name: website-values
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=values.yaml
