apiVersion: v1
kind: Secret
metadata:
    name: slskd-importer
type: Opaque
data:
    discord-webhook: ENC[AES256_GCM,data:Ijou1kZKQYnBaswTKdUY5A/VVzfniAfoXqSDQ7iiv3iOw17p9E95z3/KruqN4/60dNf/INw8FS51u9yMqEo/XIj53iSQ2IU6mRm6qSK3kGztcEVhNC+vV4mGFWTjuZ5uDkY5SservIIngtxO0oKIbxn8HSpeNBWpHQ==,iv:MIlf/wP5FqReB9tiCM2MJaP91HaGhLnnQea67VuQdUo=,tag:w4oGXQaOTqHS6uh+RYNIhA==,type:str]
sops:
    age:
        - recipient: age17kk48hynzgad60c8vdaf5phg8k9563r6mhezzhgngl3hyxrgea5q225656
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b1lYS0g4eElYUzI3R2Jl
            c2h3YTkyR2ZPV3NveVpPMjlRKy8zMkM1T0VNCld6a2tuZFg2NGp4bFpYVnBOWGZD
            U3ZwM1NlQzZtOUI2THd5Mnc2K2gzRlkKLS0tIFpCbi9kUDN5WTRxY1l1T3EydUxh
            THFTZ3NUcnJPamRyNGk5cG1oREI1RFUK+/L79rU0wPmyQYIhKpbIKXMbc7xDkJ60
            OLV27hBofEW+YA3i8B8HRwYg8mwEmkYg4pUcZLarf2yQ3yGPkC215g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T14:51:32Z"
    mac: ENC[AES256_GCM,data:MRi6ikQ8dHAdVcwdNVNERZnoIb2U9QZCkfBRHJENPMr+aNTwGuJHq6YhHg5mRwoh89ujPrN+DwAfxGrLBd2jCnNOPd+xCEJIhpS8bPPxxwpqQuoiA5So+us081XGM497Qf3Z5E65Zu1TGWm3jm2KxNwmYZD5VkbcWQyrUwfwNFY=,iv:d5ZhQDdIyANLZQxV8Wa4Yoz98Lq8JEo7ObVw1Tkf0mM=,tag:Ban6s5ctdApK7XmVuZdmWw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
