---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  main:
    replicas: 1
    containers:
      public-test:
        image:
          repository: docker.io/nginx
          tag: 1.31.4
        env:
          TZ: Europe/Vienna

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    className: traefik
    labels:
      ingress: public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.kubernetes.io/target: wallstreet30.cc
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: public-test.wallstreet30.cc
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - public-test.wallstreet30.cc
        secretName: public-test-tls

persistence:
  config:
    enabled: true
    type: configMap
    name: nginx-config
    globalMounts:
      - path: /etc/nginx/conf.d/nginx.conf
        readOnly: true
        mountPropagation: None
        subPath: nginx.conf
  content:
    enabled: true
    type: configMap
    name: nginx-content
    globalMounts:
      - path: /www/data
        readOnly: true

configMaps:
  nginx-config:
    forceRename: nginx-config
    enabled: true
    data:
      nginx.conf: |
        server {
          listen 8080;
          location / {
            root /www/data;
          }
        }
  nginx-content:
    forceRename: nginx-content
    enabled: true
    data:
      index.html: |
        <!DOCTYPE html>
        <html>
          <head>
            <title>some website</title>
          </head>
          <body>
            <h1>This is a website.</h1>
          </body>
        </html>
